export type ServerLocale = 'en' | 'es' | 'de' | 'fr' | 'it' | 'pt' | 'ru' | 'zh' | 'ja' | 'ko'

const SUPPORTED = new Set<ServerLocale>(['en', 'es', 'de', 'fr', 'it', 'pt', 'ru', 'zh', 'ja', 'ko'])

export function resolveServerLocale(languageTag: string | null | undefined): ServerLocale {
  const language = String(languageTag || '').split(',')[0].trim().split('-')[0].toLowerCase() as ServerLocale
  return SUPPORTED.has(language) ? language : 'en'
}

export function serverLocaleDirection(locale: string): 'ltr' | 'rtl' {
  return /^(ar|fa|he|ur)(-|$)/i.test(locale) ? 'rtl' : 'ltr'
}

const PAGE: Record<ServerLocale, Record<string, string>> = {
  en: { exploreCreateWall: 'Create a wall', exploreKicker: 'Discover public walls', exploreTitleLead: 'Find people worth', exploreTitleAccent: 'supporting.', exploreIntro: 'Browse by the kind of work, project, or community behind each wall, not just the amount raised.', exploreWallCount_one: '{n} public wall', exploreWallCount_other: '{n} public walls', exploreWeekTotal: '{n} NIM tipped this week', exploreUnavailableTitle: 'Public walls are temporarily unavailable', exploreUnavailableBody: 'Your walls and tips are safe. The public directory could not reach its data service.', exploreTryAgain: 'Try again', exploreNoMatchesTitle: 'No walls match those filters', exploreNoMatchesBody: 'Try a different search, or clear the filters to browse every wall.', exploreClearFilters: 'Clear filters', exploreNoFeaturedTitle: 'No featured walls yet', exploreNoFeaturedBody: 'Browse the newest walls to find someone or something to support.', exploreBrowseNewest: 'Browse newest walls', exploreNoWalls: 'No walls yet. Yours could be the first.', exploreMatching_one: '{n} matching wall', exploreMatching_other: '{n} matching walls', exploreMostTipped: 'Most supported this week', exploreUpdated: 'Updated live · last 7 days', exploreMoreCreators: 'More public walls', exploreNewCreators: 'New walls', exploreFirstSupporter: 'Be their first supporter', exploreCreateOwn: 'Create your own TipWall' },
  es: { exploreCreateWall: 'Crear un muro', exploreKicker: 'Descubre creadores', exploreTitleLead: 'Encuentra creadores que vale la pena', exploreTitleAccent: 'apoyar.', exploreIntro: 'Explora por el tipo de trabajo que crean, no solo por lo recaudado.', exploreWallCount_one: '{n} muro de creador', exploreWallCount_other: '{n} muros de creadores', exploreWeekTotal: '{n} NIM esta semana', exploreUnavailableTitle: 'Los muros no están disponibles temporalmente', exploreUnavailableBody: 'Tus muros y propinas están seguros. El directorio no pudo acceder al servicio de datos.', exploreTryAgain: 'Reintentar', exploreNoMatchesTitle: 'Ningún creador coincide con esos filtros', exploreNoMatchesBody: 'Prueba otra búsqueda o borra los filtros.', exploreClearFilters: 'Borrar filtros', exploreNoFeaturedTitle: 'Aún no hay muros destacados', exploreNoFeaturedBody: 'Explora los creadores más recientes y encuentra a quién apoyar.', exploreBrowseNewest: 'Ver muros nuevos', exploreNoWalls: 'Aún no hay muros. El tuyo podría ser el primero.', exploreMatching_one: '{n} muro coincidente', exploreMatching_other: '{n} muros coincidentes', exploreMostTipped: 'Más apoyados esta semana', exploreUpdated: 'Actualizado en vivo · últimos 7 días', exploreMoreCreators: 'Más muros de creadores', exploreNewCreators: 'Creadores nuevos', exploreFirstSupporter: 'Sé su primer apoyo', exploreCreateOwn: 'Crea tu propio TipWall' },
  de: { exploreCreateWall: 'Wand erstellen', exploreKicker: 'Creator entdecken', exploreTitleLead: 'Finde Creator, die Unterstützung', exploreTitleAccent: 'verdienen.', exploreIntro: 'Entdecke Creator nach ihrer Arbeit, nicht nur nach der gesammelten Summe.', exploreWallCount_one: '{n} Creator-Wand', exploreWallCount_other: '{n} Creator-Wände', exploreWeekTotal: '{n} NIM diese Woche', exploreUnavailableTitle: 'Creator-Wände sind vorübergehend nicht verfügbar', exploreUnavailableBody: 'Deine Wände und Trinkgelder sind sicher. Der Datendienst ist nicht erreichbar.', exploreTryAgain: 'Erneut versuchen', exploreNoMatchesTitle: 'Keine Creator entsprechen diesen Filtern', exploreNoMatchesBody: 'Versuche eine andere Suche oder lösche die Filter.', exploreClearFilters: 'Filter löschen', exploreNoFeaturedTitle: 'Noch keine vorgestellten Wände', exploreNoFeaturedBody: 'Entdecke die neuesten Creator und finde eine Wand zum Unterstützen.', exploreBrowseNewest: 'Neueste Wände ansehen', exploreNoWalls: 'Noch keine Wände. Deine könnte die erste sein.', exploreMatching_one: '{n} passende Creator-Wand', exploreMatching_other: '{n} passende Creator-Wände', exploreMostTipped: 'Diese Woche am meisten unterstützt', exploreUpdated: 'Live aktualisiert · letzte 7 Tage', exploreMoreCreators: 'Weitere Creator-Wände', exploreNewCreators: 'Neue Creator', exploreFirstSupporter: 'Sei die erste Unterstützung', exploreCreateOwn: 'Eigenes TipWall erstellen' },
  fr: { exploreCreateWall: 'Créer un mur', exploreKicker: 'Découvrir les murs publics', exploreTitleLead: 'Trouvez des personnes à', exploreTitleAccent: 'soutenir.', exploreIntro: 'Explorez selon le type de travail, de projet ou de communauté derrière chaque mur, pas seulement le montant reçu.', exploreWallCount_one: '{n} mur public', exploreWallCount_other: '{n} murs publics', exploreWeekTotal: '{n} NIM cette semaine', exploreUnavailableTitle: 'Les murs publics sont temporairement indisponibles', exploreUnavailableBody: 'Vos murs et pourboires sont en sécurité. Le répertoire public est inaccessible.', exploreTryAgain: 'Réessayer', exploreNoMatchesTitle: 'Aucun mur ne correspond à ces filtres', exploreNoMatchesBody: 'Essayez une autre recherche ou effacez les filtres pour parcourir tous les murs.', exploreClearFilters: 'Effacer les filtres', exploreNoFeaturedTitle: 'Aucun mur à la une', exploreNoFeaturedBody: 'Parcourez les nouveaux murs pour trouver une personne ou un projet à soutenir.', exploreBrowseNewest: 'Voir les nouveaux murs', exploreNoWalls: 'Aucun mur pour le moment. Le vôtre pourrait être le premier.', exploreMatching_one: '{n} mur correspondant', exploreMatching_other: '{n} murs correspondants', exploreMostTipped: 'Les plus soutenus cette semaine', exploreUpdated: 'Mis à jour en direct · 7 derniers jours', exploreMoreCreators: 'Plus de murs publics', exploreNewCreators: 'Nouveaux murs', exploreFirstSupporter: 'Soyez leur premier soutien', exploreCreateOwn: 'Créez votre TipWall' },
  it: { exploreCreateWall: 'Crea un muro', exploreKicker: 'Scopri i creator', exploreTitleLead: 'Trova creator da', exploreTitleAccent: 'sostenere.', exploreIntro: 'Esplora per tipo di lavoro, non solo per importo raccolto.', exploreWallCount_one: '{n} muro di creator', exploreWallCount_other: '{n} muri di creator', exploreWeekTotal: '{n} NIM questa settimana', exploreUnavailableTitle: 'I muri non sono temporaneamente disponibili', exploreUnavailableBody: 'Muri e mance sono al sicuro. Il servizio dati non è raggiungibile.', exploreTryAgain: 'Riprova', exploreNoMatchesTitle: 'Nessun creator corrisponde ai filtri', exploreNoMatchesBody: 'Prova un’altra ricerca o cancella i filtri.', exploreClearFilters: 'Cancella filtri', exploreNoFeaturedTitle: 'Ancora nessun muro in evidenza', exploreNoFeaturedBody: 'Scopri i creator più recenti e trova chi sostenere.', exploreBrowseNewest: 'Vedi i muri più recenti', exploreNoWalls: 'Ancora nessun muro. Il tuo potrebbe essere il primo.', exploreMatching_one: '{n} muro corrispondente', exploreMatching_other: '{n} muri corrispondenti', exploreMostTipped: 'Più sostenuti questa settimana', exploreUpdated: 'Aggiornato dal vivo · ultimi 7 giorni', exploreMoreCreators: 'Altri muri di creator', exploreNewCreators: 'Nuovi creator', exploreFirstSupporter: 'Sii il primo sostenitore', exploreCreateOwn: 'Crea il tuo TipWall' },
  pt: { exploreCreateWall: 'Criar um mural', exploreKicker: 'Descubra criadores', exploreTitleLead: 'Encontre criadores que vale', exploreTitleAccent: 'apoiar.', exploreIntro: 'Explore pelo tipo de trabalho, não apenas pelo valor arrecadado.', exploreWallCount_one: '{n} mural de criador', exploreWallCount_other: '{n} murais de criadores', exploreWeekTotal: '{n} NIM nesta semana', exploreUnavailableTitle: 'Os murais estão temporariamente indisponíveis', exploreUnavailableBody: 'Seus murais e gorjetas estão seguros. O serviço de dados está indisponível.', exploreTryAgain: 'Tentar novamente', exploreNoMatchesTitle: 'Nenhum criador corresponde aos filtros', exploreNoMatchesBody: 'Tente outra busca ou limpe os filtros.', exploreClearFilters: 'Limpar filtros', exploreNoFeaturedTitle: 'Ainda não há murais em destaque', exploreNoFeaturedBody: 'Explore os criadores mais recentes e encontre quem apoiar.', exploreBrowseNewest: 'Ver murais mais recentes', exploreNoWalls: 'Ainda não há murais. O seu pode ser o primeiro.', exploreMatching_one: '{n} mural correspondente', exploreMatching_other: '{n} murais correspondentes', exploreMostTipped: 'Mais apoiados nesta semana', exploreUpdated: 'Atualizado ao vivo · últimos 7 dias', exploreMoreCreators: 'Mais murais de criadores', exploreNewCreators: 'Novos criadores', exploreFirstSupporter: 'Seja o primeiro apoiador', exploreCreateOwn: 'Crie seu TipWall' },
  ru: { exploreCreateWall: 'Создать стену', exploreKicker: 'Поиск авторов', exploreTitleLead: 'Найдите авторов, которых стоит', exploreTitleAccent: 'поддержать.', exploreIntro: 'Ищите по типу творчества, а не только по собранной сумме.', exploreWallCount_one: '{n} стена автора', exploreWallCount_few: '{n} стены авторов', exploreWallCount_many: '{n} стен авторов', exploreWallCount_other: '{n} стен авторов', exploreWeekTotal: '{n} NIM за неделю', exploreUnavailableTitle: 'Стены временно недоступны', exploreUnavailableBody: 'Ваши стены и чаевые в безопасности. Сервис данных недоступен.', exploreTryAgain: 'Повторить', exploreNoMatchesTitle: 'Нет авторов с такими фильтрами', exploreNoMatchesBody: 'Попробуйте другой поиск или очистите фильтры.', exploreClearFilters: 'Очистить фильтры', exploreNoFeaturedTitle: 'Избранных стен пока нет', exploreNoFeaturedBody: 'Посмотрите новых авторов и найдите кого поддержать.', exploreBrowseNewest: 'Смотреть новые стены', exploreNoWalls: 'Стен пока нет. Ваша может стать первой.', exploreMatching_one: '{n} подходящая стена', exploreMatching_few: '{n} подходящие стены', exploreMatching_many: '{n} подходящих стен', exploreMatching_other: '{n} подходящих стен', exploreMostTipped: 'Больше всего поддержки за неделю', exploreUpdated: 'Обновляется · последние 7 дней', exploreMoreCreators: 'Другие стены авторов', exploreNewCreators: 'Новые авторы', exploreFirstSupporter: 'Станьте первым', exploreCreateOwn: 'Создать свой TipWall' },
  zh: { exploreCreateWall: '创建支持墙', exploreKicker: '发现创作者', exploreTitleLead: '寻找值得', exploreTitleAccent: '支持的创作者。', exploreIntro: '按创作类型浏览，而不只看筹集金额。', exploreWallCount_one: '{n} 个创作者墙', exploreWallCount_other: '{n} 个创作者墙', exploreWeekTotal: '本周打赏 {n} NIM', exploreUnavailableTitle: '创作者墙暂时不可用', exploreUnavailableBody: '你的墙和打赏是安全的，数据服务暂时无法访问。', exploreTryAgain: '重试', exploreNoMatchesTitle: '没有符合筛选条件的创作者', exploreNoMatchesBody: '尝试其他搜索或清除筛选。', exploreClearFilters: '清除筛选', exploreNoFeaturedTitle: '暂无精选墙', exploreNoFeaturedBody: '浏览最新创作者并找到想支持的人。', exploreBrowseNewest: '浏览最新墙', exploreNoWalls: '还没有墙，你可以成为第一个。', exploreMatching_one: '{n} 个匹配的创作者墙', exploreMatching_other: '{n} 个匹配的创作者墙', exploreMostTipped: '本周打赏最多', exploreUpdated: '实时更新 · 最近 7 天', exploreMoreCreators: '更多创作者墙', exploreNewCreators: '新创作者', exploreFirstSupporter: '成为他们的第一位支持者', exploreCreateOwn: '创建你的 TipWall' },
  ja: { exploreCreateWall: 'ウォールを作成', exploreKicker: 'クリエイターを発見', exploreTitleLead: '応援したいクリエイターを', exploreTitleAccent: '見つけよう。', exploreIntro: '集まった金額だけでなく、作品の種類から探せます。', exploreWallCount_one: 'クリエイターウォール {n} 件', exploreWallCount_other: 'クリエイターウォール {n} 件', exploreWeekTotal: '今週 {n} NIM', exploreUnavailableTitle: 'ウォールは一時的に利用できません', exploreUnavailableBody: 'ウォールと投げ銭は安全です。データサービスに接続できませんでした。', exploreTryAgain: '再試行', exploreNoMatchesTitle: '条件に一致するクリエイターはいません', exploreNoMatchesBody: '別の検索を試すか、フィルターを解除してください。', exploreClearFilters: 'フィルターを解除', exploreNoFeaturedTitle: '注目のウォールはまだありません', exploreNoFeaturedBody: '新しいクリエイターから応援したい人を探しましょう。', exploreBrowseNewest: '新しいウォールを見る', exploreNoWalls: 'ウォールはまだありません。最初に作ってみませんか。', exploreMatching_one: '{n} 件の一致', exploreMatching_other: '{n} 件の一致', exploreMostTipped: '今週最も応援された', exploreUpdated: 'ライブ更新 · 過去7日間', exploreMoreCreators: 'その他のウォール', exploreNewCreators: '新しいクリエイター', exploreFirstSupporter: '最初の支援者になろう', exploreCreateOwn: '自分の TipWall を作成' },
  ko: { exploreCreateWall: '벽 만들기', exploreKicker: '크리에이터 발견', exploreTitleLead: '응원할 가치가 있는 크리에이터를', exploreTitleAccent: '찾아보세요.', exploreIntro: '모금액뿐 아니라 창작 분야별로 둘러보세요.', exploreWallCount_one: '크리에이터 벽 {n}개', exploreWallCount_other: '크리에이터 벽 {n}개', exploreWeekTotal: '이번 주 {n} NIM', exploreUnavailableTitle: '크리에이터 벽을 잠시 사용할 수 없습니다', exploreUnavailableBody: '벽과 팁은 안전합니다. 데이터 서비스에 연결할 수 없습니다.', exploreTryAgain: '다시 시도', exploreNoMatchesTitle: '필터와 일치하는 크리에이터가 없습니다', exploreNoMatchesBody: '다른 검색을 시도하거나 필터를 지워보세요.', exploreClearFilters: '필터 지우기', exploreNoFeaturedTitle: '아직 추천 벽이 없습니다', exploreNoFeaturedBody: '새로운 크리에이터를 둘러보고 응원할 사람을 찾아보세요.', exploreBrowseNewest: '최신 벽 보기', exploreNoWalls: '아직 벽이 없습니다. 첫 번째 벽을 만들어보세요.', exploreMatching_one: '일치하는 벽 {n}개', exploreMatching_other: '일치하는 벽 {n}개', exploreMostTipped: '이번 주 가장 많은 후원', exploreUpdated: '실시간 업데이트 · 최근 7일', exploreMoreCreators: '더 많은 크리에이터 벽', exploreNewCreators: '새 크리에이터', exploreFirstSupporter: '첫 후원자가 되어주세요', exploreCreateOwn: '내 TipWall 만들기' },
}

// The Explore page is server-rendered, so its positioning copy cannot rely on
// the client translation module. Keep the public-wall language consistent in
// every supported locale instead of describing the directory as creator-only.
const EXPLORE_POSITIONING: Record<ServerLocale, Record<string, string>> = {
  en: { exploreKicker: 'Discover public walls', exploreTitleLead: 'Find people worth', exploreIntro: 'Browse by the kind of work, project, or community behind each wall, not just the amount raised.', exploreWallCount_one: '{n} public wall', exploreWallCount_other: '{n} public walls', exploreUnavailableTitle: 'Public walls are temporarily unavailable', exploreUnavailableBody: 'Your walls and tips are safe. The public directory could not reach its data service.', exploreNoMatchesTitle: 'No walls match those filters', exploreNoFeaturedBody: 'Browse the newest walls to find someone or something to support.', exploreMatching_one: '{n} matching wall', exploreMatching_other: '{n} matching walls', exploreMoreCreators: 'More public walls', exploreNewCreators: 'New walls' },
  es: { exploreKicker: 'Descubre muros públicos', exploreTitleLead: 'Encuentra personas que vale la pena', exploreIntro: 'Explora por el tipo de trabajo, proyecto o comunidad detrás de cada muro, no solo por lo recaudado.', exploreWallCount_one: '{n} muro público', exploreWallCount_other: '{n} muros públicos', exploreUnavailableTitle: 'Los muros públicos no están disponibles temporalmente', exploreUnavailableBody: 'Tus muros y propinas están seguros. El directorio público no pudo acceder al servicio de datos.', exploreNoMatchesTitle: 'Ningún muro coincide con esos filtros', exploreNoFeaturedBody: 'Explora los muros más recientes para encontrar a quién o qué apoyar.', exploreMatching_one: '{n} muro coincidente', exploreMatching_other: '{n} muros coincidentes', exploreMoreCreators: 'Más muros públicos', exploreNewCreators: 'Muros nuevos' },
  de: { exploreKicker: 'Öffentliche Wände entdecken', exploreTitleLead: 'Finde Menschen, die Unterstützung', exploreIntro: 'Entdecke Wände nach Arbeit, Projekt oder Community dahinter, nicht nur nach der gesammelten Summe.', exploreWallCount_one: '{n} öffentliche Wand', exploreWallCount_other: '{n} öffentliche Wände', exploreUnavailableTitle: 'Öffentliche Wände sind vorübergehend nicht verfügbar', exploreUnavailableBody: 'Deine Wände und Trinkgelder sind sicher. Das öffentliche Verzeichnis konnte den Datendienst nicht erreichen.', exploreNoMatchesTitle: 'Keine Wände entsprechen diesen Filtern', exploreNoFeaturedBody: 'Entdecke die neuesten Wände und finde jemanden oder etwas zum Unterstützen.', exploreMatching_one: '{n} passende Wand', exploreMatching_other: '{n} passende Wände', exploreMoreCreators: 'Weitere öffentliche Wände', exploreNewCreators: 'Neue Wände' },
  fr: { exploreKicker: 'Découvrir les murs publics', exploreTitleLead: 'Trouvez des personnes à', exploreIntro: 'Explorez selon le type de travail, de projet ou de communauté derrière chaque mur, pas seulement le montant reçu.', exploreWallCount_one: '{n} mur public', exploreWallCount_other: '{n} murs publics', exploreUnavailableTitle: 'Les murs publics sont temporairement indisponibles', exploreUnavailableBody: 'Vos murs et pourboires sont en sécurité. Le répertoire public est inaccessible.', exploreNoMatchesTitle: 'Aucun mur ne correspond à ces filtres', exploreNoFeaturedBody: 'Parcourez les nouveaux murs pour trouver une personne ou un projet à soutenir.', exploreMatching_one: '{n} mur correspondant', exploreMatching_other: '{n} murs correspondants', exploreMoreCreators: 'Plus de murs publics', exploreNewCreators: 'Nouveaux murs' },
  it: { exploreKicker: 'Scopri i muri pubblici', exploreTitleLead: 'Trova persone da', exploreIntro: 'Esplora per il tipo di lavoro, progetto o community dietro ogni muro, non solo per l’importo raccolto.', exploreWallCount_one: '{n} muro pubblico', exploreWallCount_other: '{n} muri pubblici', exploreUnavailableTitle: 'I muri pubblici non sono temporaneamente disponibili', exploreUnavailableBody: 'I tuoi muri e le mance sono al sicuro. La directory pubblica non può raggiungere il servizio dati.', exploreNoMatchesTitle: 'Nessun muro corrisponde ai filtri', exploreNoFeaturedBody: 'Scopri i muri più recenti e trova qualcuno o qualcosa da sostenere.', exploreMatching_one: '{n} muro corrispondente', exploreMatching_other: '{n} muri corrispondenti', exploreMoreCreators: 'Altri muri pubblici', exploreNewCreators: 'Muri nuovi' },
  pt: { exploreKicker: 'Descubra murais públicos', exploreTitleLead: 'Encontre pessoas que vale a pena', exploreIntro: 'Explore pelo tipo de trabalho, projeto ou comunidade por trás de cada mural, não apenas pelo valor arrecadado.', exploreWallCount_one: '{n} mural público', exploreWallCount_other: '{n} murais públicos', exploreUnavailableTitle: 'Os murais públicos estão temporariamente indisponíveis', exploreUnavailableBody: 'Seus murais e gorjetas estão seguros. O diretório público não conseguiu acessar o serviço de dados.', exploreNoMatchesTitle: 'Nenhum mural corresponde aos filtros', exploreNoFeaturedBody: 'Explore os murais mais recentes para encontrar alguém ou algo para apoiar.', exploreMatching_one: '{n} mural correspondente', exploreMatching_other: '{n} murais correspondentes', exploreMoreCreators: 'Mais murais públicos', exploreNewCreators: 'Murais novos' },
  ru: { exploreKicker: 'Публичные стены', exploreTitleLead: 'Найдите людей, которых стоит', exploreIntro: 'Ищите по работе, проекту или сообществу за стеной, а не только по собранной сумме.', exploreWallCount_one: '{n} публичная стена', exploreWallCount_few: '{n} публичные стены', exploreWallCount_many: '{n} публичных стен', exploreWallCount_other: '{n} публичных стен', exploreUnavailableTitle: 'Публичные стены временно недоступны', exploreUnavailableBody: 'Ваши стены и чаевые в безопасности. Публичный каталог не может получить данные.', exploreNoMatchesTitle: 'Нет стен с такими фильтрами', exploreNoFeaturedBody: 'Посмотрите новые стены и найдите человека или проект для поддержки.', exploreMatching_one: '{n} подходящая стена', exploreMatching_few: '{n} подходящие стены', exploreMatching_many: '{n} подходящих стен', exploreMatching_other: '{n} подходящих стен', exploreMoreCreators: 'Другие публичные стены', exploreNewCreators: 'Новые стены' },
  zh: { exploreKicker: '发现公开墙', exploreTitleLead: '寻找值得', exploreIntro: '按每面墙背后的工作、项目或社区浏览，而不只是看筹集金额。', exploreWallCount_one: '{n} 个公开墙', exploreWallCount_other: '{n} 个公开墙', exploreUnavailableTitle: '公开墙暂时不可用', exploreUnavailableBody: '你的墙和打赏是安全的，公开目录暂时无法访问数据服务。', exploreNoMatchesTitle: '没有符合筛选条件的墙', exploreNoFeaturedBody: '浏览最新墙，找到想支持的人或项目。', exploreMatching_one: '{n} 个匹配的墙', exploreMatching_other: '{n} 个匹配的墙', exploreMoreCreators: '更多公开墙', exploreNewCreators: '新墙' },
  ja: { exploreKicker: '公開ウォールを探す', exploreTitleLead: '応援したい人を', exploreIntro: '集まった金額だけでなく、ウォールの背景にある仕事、プロジェクト、コミュニティから探せます。', exploreWallCount_one: '公開ウォール {n} 件', exploreWallCount_other: '公開ウォール {n} 件', exploreUnavailableTitle: '公開ウォールは一時的に利用できません', exploreUnavailableBody: 'ウォールと投げ銭は安全です。公開ディレクトリに接続できませんでした。', exploreNoMatchesTitle: '条件に一致するウォールはありません', exploreNoFeaturedBody: '新しいウォールから応援したい人やプロジェクトを探しましょう。', exploreMatching_one: '{n} 件の一致', exploreMatching_other: '{n} 件の一致', exploreMoreCreators: 'その他の公開ウォール', exploreNewCreators: '新しいウォール' },
  ko: { exploreKicker: '공개 벽 둘러보기', exploreTitleLead: '응원할 사람을', exploreIntro: '모금액뿐 아니라 각 벽의 작업, 프로젝트, 커뮤니티를 기준으로 둘러보세요.', exploreWallCount_one: '공개 벽 {n}개', exploreWallCount_other: '공개 벽 {n}개', exploreUnavailableTitle: '공개 벽을 잠시 사용할 수 없습니다', exploreUnavailableBody: '벽과 팁은 안전합니다. 공개 디렉터리에 연결할 수 없습니다.', exploreNoMatchesTitle: '필터와 일치하는 벽이 없습니다', exploreNoFeaturedBody: '새로운 벽을 둘러보고 응원할 사람이나 프로젝트를 찾아보세요.', exploreMatching_one: '일치하는 벽 {n}개', exploreMatching_other: '일치하는 벽 {n}개', exploreMoreCreators: '더 많은 공개 벽', exploreNewCreators: '새 벽' },
}

const CATEGORY_KEYS = ['art', 'code', 'education', 'music', 'video', 'gaming', 'freelance', 'student', 'community'] as const
const CATEGORY_LABELS: Record<ServerLocale, string[]> = {
  en: ['Art & Design', 'Code & Open Source', 'Writing & Education', 'Music & Audio', 'Streaming & Video', 'Gaming', 'Freelance & Services', 'Student Projects', 'Community & Other'], es: ['Arte y diseño', 'Código y código abierto', 'Escritura y educación', 'Música y audio', 'Streaming y vídeo', 'Videojuegos', 'Freelance y servicios', 'Proyectos estudiantiles', 'Comunidad y otros'], de: ['Kunst & Design', 'Code & Open Source', 'Schreiben & Bildung', 'Musik & Audio', 'Streaming & Video', 'Gaming', 'Freelance & Services', 'Studentenprojekte', 'Community & Sonstiges'], fr: ['Art et design', 'Code et open source', 'Écriture et éducation', 'Musique et audio', 'Streaming et vidéo', 'Jeux vidéo', 'Freelance et services', 'Projets étudiants', 'Communauté et autres'], it: ['Arte e design', 'Codice e open source', 'Scrittura e formazione', 'Musica e audio', 'Streaming e video', 'Gaming', 'Freelance e servizi', 'Progetti studenteschi', 'Community e altro'], pt: ['Arte e design', 'Código e open source', 'Escrita e educação', 'Música e áudio', 'Streaming e vídeo', 'Jogos', 'Freelance e serviços', 'Projetos estudantis', 'Comunidade e outros'], ru: ['Искусство и дизайн', 'Код и open source', 'Тексты и образование', 'Музыка и аудио', 'Стриминг и видео', 'Игры', 'Фриланс и услуги', 'Студенческие проекты', 'Сообщество и другое'], zh: ['艺术与设计', '代码与开源', '写作与教育', '音乐与音频', '直播与视频', '游戏', '自由职业与服务', '学生项目', '社区与其他'], ja: ['アート＆デザイン', 'コード＆オープンソース', '執筆＆教育', '音楽＆音声', '配信＆動画', 'ゲーム', 'フリーランス＆サービス', '学生プロジェクト', 'コミュニティ＆その他'], ko: ['예술 및 디자인', '코드 및 오픈 소스', '글쓰기 및 교육', '음악 및 오디오', '스트리밍 및 동영상', '게임', '프리랜서 및 서비스', '학생 프로젝트', '커뮤니티 및 기타'],
}

const REASON_KEYS = ['helpful_content', 'open_source', 'tutorial', 'great_idea', 'just_support'] as const
const REASON_LABELS: Record<ServerLocale, string[]> = {
  en: ['Helpful content', 'Open source contribution', 'Tutorial / Education', 'Great idea', 'Just support'], es: ['Contenido útil', 'Contribución de código abierto', 'Tutorial / Educación', 'Gran idea', 'Solo apoyo'], de: ['Hilfreicher Inhalt', 'Open-Source-Beitrag', 'Tutorial / Bildung', 'Tolle Idee', 'Einfach unterstützen'], fr: ['Contenu utile', 'Contribution open source', 'Tutoriel / Éducation', 'Excellente idée', 'Simple soutien'], it: ['Contenuto utile', 'Contributo open source', 'Tutorial / Formazione', 'Ottima idea', 'Solo supporto'], pt: ['Conteúdo útil', 'Contribuição open source', 'Tutorial / Educação', 'Ótima ideia', 'Apenas apoio'], ru: ['Полезный контент', 'Вклад в open source', 'Обучение', 'Отличная идея', 'Просто поддержать'], zh: ['有用的内容', '开源贡献', '教程 / 教育', '好点子', '单纯支持'], ja: ['役立つコンテンツ', 'オープンソースへの貢献', 'チュートリアル / 教育', '素晴らしいアイデア', '応援'], ko: ['유용한 콘텐츠', '오픈 소스 기여', '튜토리얼 / 교육', '훌륭한 아이디어', '그냥 응원'],
}

export function serverTranslate(locale: ServerLocale, key: string, params?: Record<string, string | number>): string {
  let resolvedKey = key
  if (params && Number.isFinite(Number(params.count))) {
    const category = new Intl.PluralRules(locale).select(Number(params.count))
    resolvedKey = PAGE[locale][`${key}_${category}`] ? `${key}_${category}` : `${key}_other`
  }
  let value = EXPLORE_POSITIONING[locale][resolvedKey] || PAGE[locale][resolvedKey] || PAGE.en[resolvedKey]
  if (!value && key.startsWith('category_')) {
    const index = CATEGORY_KEYS.indexOf(key.slice(9) as typeof CATEGORY_KEYS[number])
    value = CATEGORY_LABELS[locale][index] || CATEGORY_LABELS.en[index]
  }
  if (!value && key.startsWith('reason_')) {
    const index = REASON_KEYS.indexOf(key.slice(7) as typeof REASON_KEYS[number])
    value = REASON_LABELS[locale][index] || REASON_LABELS.en[index]
  }
  value ||= key
  if (params) for (const [param, replacement] of Object.entries(params)) value = value.split(`{${param}}`).join(String(replacement))
  return value
}
